name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Claude Code Integration
        - Gemini CLI Integration
        - Copilot CLI Integration
        - Rover Orchestration
        - MCP Servers
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: ai-agent
    attributes:
      label: AI Agent (if applicable)
      description: Which AI agent were you using?
      options:
        - Claude
        - Gemini
        - Copilot
        - Not applicable

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 14]
        - Node.js version: [e.g., 22.0.0]
        - Docker version: [e.g., 24.0.0]
        - Rover version: [run `rover --version`]
        - Claude Code version: [run `claude --version`]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output (redact API keys!)
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LEEI1337/ai-dev-orchestrator/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
